package skymill

import (
 "context"
 "errors"
 "time"
 "github.com/ThreeDotsLabs/watermill"
 "github.com/ThreeDotsLabs/watermill/message"
 "github.com/ThreeDotsLabs/watermill-redisstream/pkg/redisstream"
 "github.com/redis/go-redis/v9"
)
type RedisStreamProviderConfig struct { Client redis.UniversalClient; Binding Binding; ConsumerGroup,Consumer string; MaxLen int64; NackResendSleep,BlockTime,ClaimInterval,MaxIdleTime,ConsumerTimeout time.Duration; ClaimBatchSize int64; Logger watermill.LoggerAdapter }
type redisStreamProvider struct { client redis.UniversalClient; binding Binding; group string; marshaller redisstream.Marshaller; publisher *redisstream.Publisher; subscriber *redisstream.Subscriber }
func newRedisStreamProvider(c RedisStreamProviderConfig)(*redisStreamProvider,error){ l:=c.Logger;if l==nil{l=watermill.NopLogger{}};m:=redisstream.DefaultMarshallerUnmarshaller{};ml:=map[string]int64{};if c.MaxLen>0{ml[c.Binding.Stream]=c.MaxLen};p,e:=redisstream.NewPublisher(redisstream.PublisherConfig{Client:c.Client,Marshaller:m,Maxlens:ml},l);if e!=nil{return nil,e};s,e:=redisstream.NewSubscriber(redisstream.SubscriberConfig{Client:c.Client,Consumer:c.Consumer,ConsumerGroup:c.ConsumerGroup,NackResendSleep:c.NackResendSleep,BlockTime:c.BlockTime,ClaimInterval:c.ClaimInterval,ClaimBatchSize:c.ClaimBatchSize,MaxIdleTime:c.MaxIdleTime,ConsumerTimeout:c.ConsumerTimeout,DisableIndefiniteInitialBlock:true},l);if e!=nil{_ = p.Close();return nil,e};return &redisStreamProvider{c.Client,c.Binding,c.ConsumerGroup,m,p,s},nil}
func(p *redisStreamProvider)Publish(ctx context.Context,ms ...*message.Message)error{for _,m:=range ms{m.SetContext(ctx)};return p.publisher.Publish(p.binding.Stream,ms...)}
func(p *redisStreamProvider)PublishOnce(ctx context.Context,key string,msg *message.Message,r RetentionPolicy)(PublishResult,error){v,e:=p.marshaller.Marshal(p.binding.Stream,msg);if e!=nil{return PublishResult{},e};u,_:=v[redisstream.UUIDHeaderKey].(string);m,_:=v["metadata"].([]byte);b,_:=v["payload"].([]byte);script:="local e=redis.call('GET',KEYS[1]); if e then return {e,'1'} end; local id=redis.call('XADD',KEYS[2],'*','_watermill_message_uuid',ARGV[1],'metadata',ARGV[2],'payload',ARGV[3]); if tonumber(ARGV[4])>0 then redis.call('SET',KEYS[1],id,'PX',ARGV[4]) else redis.call('SET',KEYS[1],id) end; return {id,'0'}";x,e:=p.client.Eval(ctx,script,[]string{p.binding.idempotencyKey(key),p.binding.Stream},u,m,b,r.IdempotencyTTL.Milliseconds()).Slice();if e!=nil{return PublishResult{},e};if len(x)!=2{return PublishResult{},errors.New("skymill: invalid publish-once result")};id,_:=x[0].(string);d,_:=x[1].(string);return PublishResult{ProviderDeliveryID:id,Duplicate:d=="1"},nil}
func(p *redisStreamProvider)Subscribe(ctx context.Context)(<-chan *message.Message,error){return p.subscriber.Subscribe(ctx,p.binding.Stream)}
func(p *redisStreamProvider)DeliveryState(ctx context.Context,id string)(Delivery,error){x,e:=p.client.XPendingExt(ctx,&redis.XPendingExtArgs{Stream:p.binding.Stream,Group:p.group,Start:id,End:id,Count:1}).Result();if e!=nil{return Delivery{},e};if len(x)==0||x[0].ID!=id{return Delivery{},errors.New("skymill: delivery is not pending")};return Delivery{ProviderDeliveryID:x[0].ID,ConsumerGroup:p.group,Consumer:x[0].Consumer,Attempt:x[0].RetryCount,Idle:x[0].Idle},nil}
func(p *redisStreamProvider)DeadLetter(ctx context.Context,d Delivery,msg *message.Message,stream string)error{v,e:=p.marshaller.Marshal(stream,msg);if e!=nil{return e};u,_:=v[redisstream.UUIDHeaderKey].(string);m,_:=v["metadata"].([]byte);b,_:=v["payload"].([]byte);script:="local e=redis.call('GET',KEYS[1]);if e then return e end;local id=redis.call('XADD',KEYS[2],'*','_watermill_message_uuid',ARGV[1],'metadata',ARGV[2],'payload',ARGV[3]);redis.call('SET',KEYS[1],id);return id";_,e=p.client.Eval(ctx,script,[]string{p.binding.idempotencyKey("dlq:"+d.ConsumerGroup+":"+d.ProviderDeliveryID),stream},u,m,b).Result();return e}
func(p *redisStreamProvider)Ack(ctx context.Context,g,id string)(bool,error){n,e:=p.client.XAck(ctx,p.binding.Stream,g,id).Result();return n>0,e}
func(p *redisStreamProvider)Status(ctx context.Context)(ProviderStatus,error){var s ProviderStatus;n,e:=p.client.XLen(ctx,p.binding.Stream).Result();if e!=nil&&e!=redis.Nil{return s,e};s.StreamLength=n;if p.group==""{return s,nil};x,e:=p.client.XPending(ctx,p.binding.Stream,p.group).Result();if e!=nil&&e!=redis.Nil{return s,e};if x!=nil{s.Pending=PendingStats{Count:x.Count,LowestID:x.Lower,HighestID:x.Higher,Consumers:int64(len(x.Consumers))}};cs,e:=p.client.XInfoConsumers(ctx,p.binding.Stream,p.group).Result();if e!=nil&&e!=redis.Nil{return s,e};s.Consumers=int64(len(cs));if s.Pending.Count>0{x,e:=p.client.XPendingExt(ctx,&redis.XPendingExtArgs{Stream:p.binding.Stream,Group:p.group,Start:"-",End:"+",Count:1}).Result();if e!=nil&&e!=redis.Nil{return s,e};if len(x)>0{s.OldestPendingIdle=x[0].Idle}};return s,nil}
func(p *redisStreamProvider)Close()error{var x error;if e:=p.subscriber.Close();e!=nil{x=e};if e:=p.publisher.Close();e!=nil&&x==nil{x=e};return x}
